---
- name: epel repo check for not aliyun ecs
  tags: php72-epel
  block:
    - name: ensure epel repo is exist (not aliyun ecs)
      stat:
        path: /etc/yum.repos.d/epel.repo
      register: epel_repo

    - name: copy epel repo if is not exist  (not aliyun ecs)
      copy:
        src: "epel_{{ ansible_facts.distribution_major_version }}.repo"
        dest: /etc/yum.repos.d/epel.repo
        owner: root
        group: root
        mode: '0644'
      when:
        - not epel_repo.stat.exists
  when:
    - "'alibaba' not in ansible_facts.product_name.lower()"

- name: install dependency packages for php 7.2
  tags: php72-packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - gcc-c++
    - openssl
    - openssl-devel
    - zip
    - zlib
    - zlib-devel
    - pcre
    - pcre-devel
    - mhash
    - mhash-devel
    - gd
    - gd-devel

- name: copy remi repo to destination
  tags: php72-repo
  copy:
    src: remi.repo
    dest: /etc/yum.repos.d/remi.repo
    owner: root
    group: root
    mode: '0644'

- name: install packages for php 7.2
  tags: php72-packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - php72
    - php72-php
    - php72-runtime
    - php72-php-bcmath
    - php72-php-cli
    - php72-php-common
    - php72-php-devel
    - php72-php-fpm
    - php72-php-gd
    - php72-php-intl
    - php72-php-json
    - php72-php-mbstring
    - php72-php-mysqlnd
    - php72-php-opcache
    - php72-php-pdo
    - php72-php-soap
    - php72-php-xml
    - php72-php-xmlrpc
    - php72-php-dba
    - php72-php-enchant
    - php72-php-gmp
    - php72-php-imap
    - php72-php-json
    - php72-php-ldap
    - php72-php-odbc
    - php72-php-pdo-dblib
    - php72-php-interbase
    - php72-php-pgsql
    - php72-php-pspell
    - php72-php-recode
    - php72-php-sodium
    - php72-php-tidy
    - php72-php-lz4
    - php72-php-process
    - php72-php-pecl-crypto
    - php72-php-pecl-decimal
    - php72-php-pecl-http-devel
    - php72-php-pecl-http
    - php72-php-pecl-imagick
    - php72-php-pecl-imagick-devel
    - php72-php-pecl-mcrypt
    - php72-php-pecl-mysql
    - php72-php-pecl-oauth
    - php72-php-pecl-redis
    - php72-php-pecl-request
    - php72-php-pecl-seaslog
    - php72-php-pecl-swoole
    - php72-php-phalcon3
    - php72-php-pecl-apcu
    - php72-php-pecl-geoip
    - php72-php-pecl-libsodium
    - php72-php-pecl-memcached
    - php72-php-pecl-mongodb
    - php72-php-pecl-zip
